spring:
  application:
    name: scm-product-api
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 7001



# httpConnPool 설정
httpconnpool:
  max-total: 20
  default-max-per-route: 20
  max-pending: 50
  connection-request-timeout: 3000
  connection-timeout: 3000
  socket-timeout: 3000