server:
    port: 7002
spring:
    application:
        name: core-titan-api
    mvc:
        throw-exception-if-no-handler-found: true
    profiles:
        active: local
    web:
        resources:
            add-mappings: false
            
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
  - /v1/**