spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    database: 0
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  datasource:
    hikari:
      auto-commit: false
      connection-test-query: select 1 from dual
      connection-timeout: 60000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

server:
  port: 7001



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:sql/**/*.xml

# httpConnPool 설정
httpconnpool:
  max-total: 20
  default-max-per-route: 20
  max-pending: 50
  connection-request-timeout: 3000
  connection-timeout: 3000
  socket-timeout: 3000